#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import tempfile

ROOT = Path(__file__).resolve().parents[2]
FIXTURE_DIR = ROOT / "zigux" / "tests" / "fixtures" / "fixdep"

EXPECTED_PACKET = {
    "sample_double_backslash_comment.d": (
        "sample_double_backslash_comment.o: "
        "zigux/tests/fixtures/fixdep/sample_double_backslash_comment_source.rmeta "
        "zigux/tests/fixtures/fixdep/missing\\\\\\\\#dep.h \\\n"
        "# generated by rustc\\\\\\\\\n"
        "  include/generated/autoconf.h zigux/tests/fixtures/fixdep/dep\\ name.rmeta\n"
    ),
    "sample_double_backslash_comment_expected.txt": (
        "savedcmd_sample_double_backslash_comment.o := "
        "rustc --emit dep-info=sample_double_backslash_comment.d\n\n"
        "source_sample_double_backslash_comment.o := "
        "zigux/tests/fixtures/fixdep/sample_double_backslash_comment_source.rmeta\n\n"
        "deps_sample_double_backslash_comment.o := \\\n"
        "  zigux/tests/fixtures/fixdep/missing\\\\\\\\ \\\n"
    ),
    "sample_double_backslash_comment_expected.stderr.txt": (
        "fixdep: error opening file: "
        "zigux/tests/fixtures/fixdep/missing\\\\\\\\: No such file or directory\n"
    ),
}

EXPECTED_SELF_TEST_CASE_COUNT = 4


def validate_packet(fixture_dir: Path = FIXTURE_DIR) -> None:
    for name, expected in EXPECTED_PACKET.items():
        path = fixture_dir / name
        if not path.exists():
            raise FileNotFoundError(f"{path}:missing_fixture")
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            raise ValueError(f"{path}:content_drift")


def expect_failure(label: str, callback, expected_message: str) -> None:
    try:
        callback()
    except (FileNotFoundError, ValueError) as exc:
        if str(exc) != expected_message:
            raise SystemExit(
                f"double_backslash:self-test:{label}:expected={expected_message!r}:actual={str(exc)!r}"
            ) from exc
        return
    raise SystemExit(f"double_backslash:self-test:{label}:missing_failure:{expected_message!r}")


def run_self_test() -> int:
    checks_run = 0

    validate_packet()
    checks_run += 1

    with tempfile.TemporaryDirectory(prefix="zigux_fixdep_double_backslash_missing_") as tmp_dir:
        fixture_dir = Path(tmp_dir)
        for name, expected in EXPECTED_PACKET.items():
            if name == "sample_double_backslash_comment_expected.stderr.txt":
                continue
            (fixture_dir / name).write_text(expected, encoding="utf-8")
        expect_failure(
            "missing_fixture",
            lambda: validate_packet(fixture_dir),
            f"{fixture_dir / 'sample_double_backslash_comment_expected.stderr.txt'}:missing_fixture",
        )
    checks_run += 1

    with tempfile.TemporaryDirectory(prefix="zigux_fixdep_double_backslash_depfile_drift_") as tmp_dir:
        fixture_dir = Path(tmp_dir)
        for name, expected in EXPECTED_PACKET.items():
            content = expected
            if name == "sample_double_backslash_comment.d":
                content = content.replace("dep\\ name.rmeta", "dep\\ other.rmeta")
            (fixture_dir / name).write_text(content, encoding="utf-8")
        expect_failure(
            "depfile_drift",
            lambda: validate_packet(fixture_dir),
            f"{fixture_dir / 'sample_double_backslash_comment.d'}:content_drift",
        )
    checks_run += 1

    with tempfile.TemporaryDirectory(prefix="zigux_fixdep_double_backslash_stderr_drift_") as tmp_dir:
        fixture_dir = Path(tmp_dir)
        for name, expected in EXPECTED_PACKET.items():
            content = expected
            if name == "sample_double_backslash_comment_expected.stderr.txt":
                content = content.replace("No such file or directory", "Permission denied")
            (fixture_dir / name).write_text(content, encoding="utf-8")
        expect_failure(
            "stderr_drift",
            lambda: validate_packet(fixture_dir),
            f"{fixture_dir / 'sample_double_backslash_comment_expected.stderr.txt'}:content_drift",
        )
    checks_run += 1

    assert checks_run == EXPECTED_SELF_TEST_CASE_COUNT
    print("FIXDEP_DOUBLE_BACKSLASH_PACKET=pass")
    print(f"FIXDEP_DOUBLE_BACKSLASH_PACKET_SELF_TEST_CASE_COUNT={checks_run}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check the widened double-backslash fixdep fixture packet stays exact."
    )
    parser.add_argument("--self-test", action="store_true", help="Run built-in packet guard self-tests.")
    args = parser.parse_args()

    if args.self_test:
        return run_self_test()

    validate_packet()
    print("FIXDEP_DOUBLE_BACKSLASH_PACKET=pass")
    print(f"FIXTURE_DIR={FIXTURE_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
