const std = @import("std");
const fixdep = @import("fixdep.zig");

const Capture = struct {
    list: std.ArrayList(u8),
    allocator: std.mem.Allocator,

    fn init(allocator: std.mem.Allocator) !Capture {
        return .{
            .list = try std.ArrayList(u8).initCapacity(allocator, 512),
            .allocator = allocator,
        };
    }

    fn deinit(self: *Capture) void {
        self.list.deinit(self.allocator);
    }

    pub fn print(self: *Capture, comptime fmt: []const u8, args: anytype) !void {
        const rendered = try std.fmt.allocPrint(self.allocator, fmt, args);
        defer self.allocator.free(rendered);
        try self.list.appendSlice(self.allocator, rendered);
    }

    pub fn flush(_: *Capture) !void {}
};

test "runFixdep accepts CRLF dependency continuations through the public entry path" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "source.c",
        .data = "CONFIG_ZIGUX_CRLF_SOURCE\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "header.h",
        .data = "CONFIG_ZIGUX_CRLF_HEADER_MODULE\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "repeated.h",
        .data = "CONFIG_ZIGUX_CRLF_REPEATED\n",
    });
    const source_path = try std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}/source.c",
        .{tmp.sub_path[0..]},
    );
    defer std.testing.allocator.free(source_path);

    const header_path = try std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}/header.h",
        .{tmp.sub_path[0..]},
    );
    defer std.testing.allocator.free(header_path);

    const repeated_path = try std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}/repeated.h",
        .{tmp.sub_path[0..]},
    );
    defer std.testing.allocator.free(repeated_path);

    const autoconf_path = try std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}/include/generated/autoconf.h",
        .{tmp.sub_path[0..]},
    );
    defer std.testing.allocator.free(autoconf_path);

    try tmp.dir.createDirPath(std.testing.io, "include/generated");
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "include/generated/autoconf.h",
        .data = "CONFIG_ZIGUX_CRLF_AUTOCONF_SHOULD_NOT_PARSE\n",
    });

    const depfile_bytes = try std.fmt.allocPrint(
        std.testing.allocator,
        "crlf.o: {s} \\\r\n" ++
            " {s} \\\r\n" ++
            " {s}\r\n" ++
            "# generated by rustc\\\r\n" ++
            " still comment text CONFIG_ZIGUX_CRLF_COMMENT_SHOULD_NOT_PARSE\r\n" ++
            "module/crlf.o: ignored.rmeta {s}\r\n",
        .{ source_path, header_path, autoconf_path, repeated_path },
    );
    defer std.testing.allocator.free(depfile_bytes);

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "crlf.d",
        .data = depfile_bytes,
    });

    const depfile_path = try std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}/crlf.d",
        .{tmp.sub_path[0..]},
    );
    defer std.testing.allocator.free(depfile_path);

    var capture = try Capture.init(std.testing.allocator);
    defer capture.deinit();

    try fixdep.runFixdep(
        std.testing.allocator,
        std.testing.io,
        &capture,
        depfile_path,
        "crlf.o",
        "rustc --emit dep-info=crlf.d",
    );

    const expected = try std.fmt.allocPrint(
        std.testing.allocator,
        "savedcmd_crlf.o := rustc --emit dep-info=crlf.d\n\n" ++
            "source_crlf.o := {s}\n\n" ++
            "deps_crlf.o := \\\n" ++
            "    $(wildcard include/config/ZIGUX_CRLF_SOURCE) \\\n" ++
            "  {s} \\\n" ++
            "    $(wildcard include/config/ZIGUX_CRLF_HEADER) \\\n" ++
            "  {s} \\\n" ++
            "    $(wildcard include/config/ZIGUX_CRLF_REPEATED) \\\n" ++
            "\n" ++
            "crlf.o: $(deps_crlf.o)\n\n" ++
            "$(deps_crlf.o):\n",
        .{ source_path, header_path, repeated_path },
    );
    defer std.testing.allocator.free(expected);

    try std.testing.expectEqualStrings(expected, capture.list.items);
    try std.testing.expect(std.mem.indexOf(u8, capture.list.items, "AUTOCONF_SHOULD_NOT_PARSE") == null);
    try std.testing.expect(std.mem.indexOf(u8, capture.list.items, "COMMENT_SHOULD_NOT_PARSE") == null);
}
