const std = @import("std");
const fixdep = @import("fixdep.zig");

test "fixdep dedupes repeated dependency headers and later repeated deps on the public entry path" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const relative_base_path = try std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}",
        .{tmp.sub_path[0..]},
    );
    defer std.testing.allocator.free(relative_base_path);

    const base_path = try std.Io.Dir.cwd().realPathFileAlloc(std.testing.io, relative_base_path, std.testing.allocator);
    defer std.testing.allocator.free(base_path);

    const source_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_repeat_dedupe_source.c",
        .{base_path},
    );
    defer std.testing.allocator.free(source_path);

    const first_config_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_repeat_dedupe_first-config.h",
        .{base_path},
    );
    defer std.testing.allocator.free(first_config_dep_path);

    const second_config_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_repeat_dedupe_second-config.h",
        .{base_path},
    );
    defer std.testing.allocator.free(second_config_dep_path);

    const repeated_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_repeat_dedupe_dep.so",
        .{base_path},
    );
    defer std.testing.allocator.free(repeated_dep_path);

    const depfile_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_repeat_dedupe.d",
        .{base_path},
    );
    defer std.testing.allocator.free(depfile_path);

    const cmdline = try std.fmt.allocPrint(
        std.testing.allocator,
        "clang -c {s} -o sample_repeat_dedupe.o",
        .{source_path},
    );
    defer std.testing.allocator.free(cmdline);

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_repeat_dedupe_source.c",
        .data = "int zigux_fixdep_sample_repeat_dedupe(void) { return 0; }\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_repeat_dedupe_first-config.h",
        .data = "#define CONFIG_ZIGUX_REPEAT_CHAIN 1\n" ++
            "#define CONFIG_ZIGUX_SHARED_CHAIN_MODULE 1\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_repeat_dedupe_second-config.h",
        .data = "#define CONFIG_ZIGUX_SHARED_CHAIN_MODULE 1\n" ++
            "#define CONFIG_ZIGUX_SECOND_CHAIN 1\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_repeat_dedupe_dep.so",
        .data = "",
    });

    const depfile_text = try std.fmt.allocPrint(
        std.testing.allocator,
        "sample_repeat_dedupe.o: {s} {s} {s} \\\n" ++
            " {s}\n" ++
            "# generated by rustc\\\\\n" ++
            "still inside the comment block\n" ++
            "sample_repeat_dedupe.o: ignored_second_source.rmeta {s} {s} {s} {s}\n",
        .{
            source_path,
            first_config_dep_path,
            repeated_dep_path,
            second_config_dep_path,
            repeated_dep_path,
            first_config_dep_path,
            second_config_dep_path,
            repeated_dep_path,
        },
    );
    defer std.testing.allocator.free(depfile_text);

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_repeat_dedupe.d",
        .data = depfile_text,
    });

    const Capture = struct {
        list: std.ArrayList(u8),
        allocator: std.mem.Allocator,

        fn init(allocator: std.mem.Allocator) !@This() {
            return .{
                .list = try std.ArrayList(u8).initCapacity(allocator, 512),
                .allocator = allocator,
            };
        }

        fn deinit(self: *@This()) void {
            self.list.deinit(self.allocator);
        }

        pub fn print(self: *@This(), comptime fmt: []const u8, args: anytype) !void {
            const rendered = try std.fmt.allocPrint(self.allocator, fmt, args);
            defer self.allocator.free(rendered);
            try self.list.appendSlice(self.allocator, rendered);
        }

        pub fn flush(_: *@This()) !void {}
    };

    var capture = try Capture.init(std.testing.allocator);
    defer capture.deinit();

    try fixdep.runFixdep(
        std.testing.allocator,
        std.testing.io,
        &capture,
        depfile_path,
        "sample_repeat_dedupe.o",
        cmdline,
    );

    const expected = try std.fmt.allocPrint(
        std.testing.allocator,
        "savedcmd_sample_repeat_dedupe.o := {s}\n\n" ++
            "source_sample_repeat_dedupe.o := {s}\n\n" ++
            "deps_sample_repeat_dedupe.o := \\\n" ++
            "  {s} \\\n" ++
            "    $(wildcard include/config/ZIGUX_REPEAT_CHAIN) \\\n" ++
            "    $(wildcard include/config/ZIGUX_SHARED_CHAIN) \\\n" ++
            "  {s} \\\n" ++
            "  {s} \\\n" ++
            "    $(wildcard include/config/ZIGUX_SECOND_CHAIN) \\\n" ++
            "\n" ++
            "sample_repeat_dedupe.o: $(deps_sample_repeat_dedupe.o)\n\n" ++
            "$(deps_sample_repeat_dedupe.o):\n",
        .{
            cmdline,
            source_path,
            first_config_dep_path,
            repeated_dep_path,
            second_config_dep_path,
        },
    );
    defer std.testing.allocator.free(expected);

    try std.testing.expectEqualStrings(expected, capture.list.items);
}
