const std = @import("std");

test "fixdep keeps later config deps after continued comment blocks on the public entry path" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const relative_base_path = try std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}",
        .{tmp.sub_path[0..]},
    );
    defer std.testing.allocator.free(relative_base_path);

    const base_path = try std.Io.Dir.cwd().realPathFileAlloc(std.testing.io, relative_base_path, std.testing.allocator);
    defer std.testing.allocator.free(base_path);

    const source_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_comment_chain_source.c",
        .{base_path},
    );
    defer std.testing.allocator.free(source_path);

    const config_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_comment_chain-config.h",
        .{base_path},
    );
    defer std.testing.allocator.free(config_dep_path);

    const later_config_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_comment_chain_later-config.h",
        .{base_path},
    );
    defer std.testing.allocator.free(later_config_dep_path);

    const later_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_comment_chain_later_dep.so",
        .{base_path},
    );
    defer std.testing.allocator.free(later_dep_path);

    const depfile_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_comment_chain.d",
        .{base_path},
    );
    defer std.testing.allocator.free(depfile_path);

    const cmdline = try std.fmt.allocPrint(
        std.testing.allocator,
        "clang -c {s} -o sample_comment_chain.o",
        .{source_path},
    );
    defer std.testing.allocator.free(cmdline);

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_comment_chain_source.c",
        .data = "int zigux_fixdep_sample_comment_chain(void) { return 0; }\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_comment_chain-config.h",
        .data = "#define CONFIG_ZIGUX_CHAIN 1\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_comment_chain_later-config.h",
        .data = "#define CONFIG_ZIGUX_LATER_CHAIN_MODULE 1\n" ++
            "#define CONFIG_ZIGUX_LATER_CHAIN 1\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_comment_chain_later_dep.so",
        .data = "",
    });

    const depfile_text = try std.fmt.allocPrint(
        std.testing.allocator,
        "sample_comment_chain.o: {s} \\\n" ++
            " {s}\n" ++
            "# generated by rustc\\\\\n" ++
            "still inside the continued comment\\\\\n" ++
            "before the next real target\n" ++
            "sample_comment_chain.o: ignored_second_source.rmeta {s} {s}\n",
        .{ source_path, config_dep_path, later_config_dep_path, later_dep_path },
    );
    defer std.testing.allocator.free(depfile_text);

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_comment_chain.d",
        .data = depfile_text,
    });

    const argv: []const []const u8 = &.{
        "zig",
        "run",
        "fixdep.zig",
        "--",
        depfile_path,
        "sample_comment_chain.o",
        cmdline,
    };
    const result = try std.process.run(std.testing.allocator, std.testing.io, .{
        .argv = argv,
        .cwd = .{ .path = "." },
        .stdout_limit = .unlimited,
        .stderr_limit = .unlimited,
    });
    defer std.testing.allocator.free(result.stdout);
    defer std.testing.allocator.free(result.stderr);

    try std.testing.expectEqual(std.process.Child.Term{ .exited = 0 }, result.term);

    const expected = try std.fmt.allocPrint(
        std.testing.allocator,
        "savedcmd_sample_comment_chain.o := {s}\n\n" ++
            "source_sample_comment_chain.o := {s}\n\n" ++
            "deps_sample_comment_chain.o := \\\n" ++
            "  {s} \\\n" ++
            "    $(wildcard include/config/ZIGUX_CHAIN) \\\n" ++
            "  {s} \\\n" ++
            "    $(wildcard include/config/ZIGUX_LATER_CHAIN) \\\n" ++
            "  {s} \\\n" ++
            "\n" ++
            "sample_comment_chain.o: $(deps_sample_comment_chain.o)\n\n" ++
            "$(deps_sample_comment_chain.o):\n",
        .{ cmdline, source_path, config_dep_path, later_config_dep_path, later_dep_path },
    );
    defer std.testing.allocator.free(expected);

    try std.testing.expectEqualStrings(expected, result.stdout);
    try std.testing.expectEqualStrings("", result.stderr);
}
