const std = @import("std");

fn tmpBasePath(tmp: anytype) ![]u8 {
    return std.fmt.allocPrint(
        std.testing.allocator,
        "scripts/zigux/.zig-cache/tmp/{s}",
        .{tmp.sub_path[0..]},
    );
}

test "fixdep keeps escaped colon dependencies visible across CRLF comment concatenation on the public entry path" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const base_path = try tmpBasePath(tmp);
    defer std.testing.allocator.free(base_path);

    const target = "sample_comment_crlf_concat.o";
    const source_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_comment_crlf_source.rmeta",
        .{base_path},
    );
    defer std.testing.allocator.free(source_path);

    const first_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/dep-first.so",
        .{base_path},
    );
    defer std.testing.allocator.free(first_dep_path);

    const ignored_source_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/ignored-source.rmeta",
        .{base_path},
    );
    defer std.testing.allocator.free(ignored_source_path);

    const escaped_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/dir\\:crate.rmeta",
        .{base_path},
    );
    defer std.testing.allocator.free(escaped_dep_path);

    const visible_escaped_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/dir:crate.rmeta",
        .{base_path},
    );
    defer std.testing.allocator.free(visible_escaped_dep_path);

    const later_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/later.rmeta",
        .{base_path},
    );
    defer std.testing.allocator.free(later_dep_path);

    const depfile_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_comment_crlf_concat.d",
        .{base_path},
    );
    defer std.testing.allocator.free(depfile_path);

    const cmdline = try std.fmt.allocPrint(
        std.testing.allocator,
        "clang -c {s} -o {s}",
        .{ source_path, target },
    );
    defer std.testing.allocator.free(cmdline);

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_comment_crlf_source.rmeta",
        .data = "",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "dep-first.so",
        .data = "",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "later.rmeta",
        .data = "",
    });

    const depfile_text = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}: {s} {s} \\\r\n# generated by rustc\\\\\r\n  still comment\r\nmodule/{s}: {s} {s} {s}\r\n",
        .{ target, source_path, first_dep_path, target, ignored_source_path, escaped_dep_path, later_dep_path },
    );
    defer std.testing.allocator.free(depfile_text);

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_comment_crlf_concat.d",
        .data = depfile_text,
    });

    const expected = try std.fmt.allocPrint(
        std.testing.allocator,
        "savedcmd_{s} := {s}\n\n" ++
            "source_{s} := {s}\n\n" ++
            "deps_{s} := \\\n" ++
            "  {s} \\\n" ++
            "  {s} \\\n" ++
            "  {s} \\\n" ++
            "\n" ++
            "{s}: $(deps_{s})\n\n" ++
            "$(deps_{s}):\n",
        .{
            target,
            cmdline,
            target,
            source_path,
            target,
            first_dep_path,
            visible_escaped_dep_path,
            later_dep_path,
            target,
            target,
            target,
        },
    );
    defer std.testing.allocator.free(expected);

    const argv: []const []const u8 = &.{
        "/usr/bin/env",
        "zig",
        "run",
        "scripts/zigux/fixdep.zig",
        "--",
        depfile_path,
        target,
        cmdline,
    };

    const result = try std.process.run(std.testing.allocator, std.testing.io, .{
        .argv = argv,
        .cwd = .{ .path = "../.." },
        .stdout_limit = .unlimited,
        .stderr_limit = .unlimited,
    });
    defer std.testing.allocator.free(result.stdout);
    defer std.testing.allocator.free(result.stderr);

    try std.testing.expectEqual(std.process.Child.Term{ .exited = 0 }, result.term);
    try std.testing.expectEqualStrings(expected, result.stdout);
    try std.testing.expectEqualStrings("", result.stderr);
}
