const std = @import("std");
const fixdep = @import("fixdep.zig");

const Capture = struct {
    list: std.ArrayList(u8),
    allocator: std.mem.Allocator,

    fn init(allocator: std.mem.Allocator) !@This() {
        return .{
            .list = try std.ArrayList(u8).initCapacity(allocator, 512),
            .allocator = allocator,
        };
    }

    fn deinit(self: *@This()) void {
        self.list.deinit(self.allocator);
    }

    pub fn print(self: *@This(), comptime fmt: []const u8, args: anytype) !void {
        const rendered = try std.fmt.allocPrint(self.allocator, fmt, args);
        defer self.allocator.free(rendered);
        try self.list.appendSlice(self.allocator, rendered);
    }

    pub fn flush(_: *@This()) !void {}
};

test "runFixdep keeps concatenated dependency targets aligned with the first target packet" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const base_path = try std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}",
        .{tmp.sub_path[0..]},
    );
    defer std.testing.allocator.free(base_path);

    const source_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_concatenated_source.c",
        .{base_path},
    );
    defer std.testing.allocator.free(source_path);

    const header_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_concatenated_dep.h",
        .{base_path},
    );
    defer std.testing.allocator.free(header_path);

    const temp_source_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_concatenated_temp.c",
        .{base_path},
    );
    defer std.testing.allocator.free(temp_source_path);

    const temp_header_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_concatenated_temp_dep.h",
        .{base_path},
    );
    defer std.testing.allocator.free(temp_header_path);

    const depfile_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_concatenated.d",
        .{base_path},
    );
    defer std.testing.allocator.free(depfile_path);

    const cmdline = try std.fmt.allocPrint(
        std.testing.allocator,
        "clang -c {s} -o sample_concatenated.o",
        .{source_path},
    );
    defer std.testing.allocator.free(cmdline);

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_concatenated_source.c",
        .data = "/* CONFIG_ZIGUX_DT_SOURCE */\nint zigux_fixdep_sample_concatenated(void) { return 0; }\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_concatenated_dep.h",
        .data = "#define CONFIG_ZIGUX_DT_HEADER 1\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_concatenated_temp.c",
        .data = "int zigux_fixdep_sample_concatenated_temp(void) { return 0; }\n",
    });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_concatenated_temp_dep.h",
        .data = "#define CONFIG_ZIGUX_DT_SECONDARY 1\n",
    });
    const depfile_text = try std.fmt.allocPrint(
        std.testing.allocator,
        "sample_concatenated.o: {s} {s} \\\n" ++
            "# generated by rustc\\\\\n" ++
            "  still comment\n" ++
            "module/sample_concatenated.o: {s} {s} \\\n" ++
            " include/generated/autoconf.h \\\n" ++
            " {s}\n",
        .{ source_path, header_path, temp_source_path, temp_header_path, temp_header_path },
    );
    defer std.testing.allocator.free(depfile_text);

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_concatenated.d",
        .data = depfile_text,
    });

    var capture = try Capture.init(std.testing.allocator);
    defer capture.deinit();

    try fixdep.runFixdep(
        std.testing.allocator,
        std.testing.io,
        &capture,
        depfile_path,
        "sample_concatenated.o",
        cmdline,
    );

    const expected = try std.fmt.allocPrint(
        std.testing.allocator,
        "savedcmd_sample_concatenated.o := {s}\n\n" ++
            "source_sample_concatenated.o := {s}\n\n" ++
            "deps_sample_concatenated.o := \\\n" ++
            "    $(wildcard include/config/ZIGUX_DT_SOURCE) \\\n" ++
            "  {s} \\\n" ++
            "    $(wildcard include/config/ZIGUX_DT_HEADER) \\\n" ++
            "  {s} \\\n" ++
            "    $(wildcard include/config/ZIGUX_DT_SECONDARY) \\\n" ++
            "\n" ++
            "sample_concatenated.o: $(deps_sample_concatenated.o)\n\n" ++
            "$(deps_sample_concatenated.o):\n",
        .{ cmdline, source_path, header_path, temp_header_path },
    );
    defer std.testing.allocator.free(expected);

    try std.testing.expectEqualStrings(expected, capture.list.items);
}
