const std = @import("std");

test "fixdep keeps comment-only depfile parse errors aligned on the public entry path" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const base_path = try std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}",
        .{tmp.sub_path[0..]},
    );
    defer std.testing.allocator.free(base_path);

    const depfile_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_comment_only.d",
        .{base_path},
    );
    defer std.testing.allocator.free(depfile_path);

    const cmdline = "clang -c sample_comment_only_source.c -o sample_comment_only.o";

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_comment_only.d",
        .data = "# generated by rustc\\\\\ncontinued comment line\\\\\nstill no real targets\n",
    });

    const argv: []const []const u8 = &.{
        "zig",
        "run",
        "fixdep.zig",
        "--",
        depfile_path,
        "sample_comment_only.o",
        cmdline,
    };
    const result = try std.process.run(std.testing.allocator, std.testing.io, .{
        .argv = argv,
        .cwd = .{ .path = "." },
        .stdout_limit = .unlimited,
        .stderr_limit = .unlimited,
    });
    defer std.testing.allocator.free(result.stdout);
    defer std.testing.allocator.free(result.stderr);

    try std.testing.expectEqual(std.process.Child.Term{ .exited = 1 }, result.term);
    try std.testing.expectEqualStrings(
        "savedcmd_sample_comment_only.o := " ++ cmdline ++ "\n\n",
        result.stdout,
    );
    try std.testing.expectEqualStrings(
        "fixdep: parse error; no targets found\n",
        result.stderr,
    );
}
