const std = @import("std");
const fixdep = @import("fixdep.zig");

const Capture = struct {
    list: std.ArrayList(u8),
    allocator: std.mem.Allocator,

    fn init(allocator: std.mem.Allocator, capacity: usize) !@This() {
        return .{
            .list = try std.ArrayList(u8).initCapacity(allocator, capacity),
            .allocator = allocator,
        };
    }

    fn deinit(self: *@This()) void {
        self.list.deinit(self.allocator);
    }

    pub fn print(self: *@This(), comptime fmt: []const u8, args: anytype) !void {
        const rendered = try std.fmt.allocPrint(self.allocator, fmt, args);
        defer std.testing.allocator.free(rendered);
        try self.list.appendSlice(self.allocator, rendered);
    }

    pub fn flush(_: *@This()) !void {}
};

fn tmpBasePath(tmp: anytype) ![]u8 {
    return std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}",
        .{tmp.sub_path[0..]},
    );
}

test "runFixdep keeps escaped colon dependencies visible across CRLF comment concatenation" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const base_path = try tmpBasePath(tmp);
    defer std.testing.allocator.free(base_path);

    const source_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_comment_crlf_source.rmeta",
        .{base_path},
    );
    defer std.testing.allocator.free(source_path);

    const first_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/dep-first.so",
        .{base_path},
    );
    defer std.testing.allocator.free(first_dep_path);

    const ignored_source_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/ignored-source.rmeta",
        .{base_path},
    );
    defer std.testing.allocator.free(ignored_source_path);

    const escaped_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/dir\\\\:crate.rmeta",
        .{base_path},
    );
    defer std.testing.allocator.free(escaped_dep_path);

    const visible_escaped_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/dir:crate.rmeta",
        .{base_path},
    );
    defer std.testing.allocator.free(visible_escaped_dep_path);

    const later_dep_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/later.rmeta",
        .{base_path},
    );
    defer std.testing.allocator.free(later_dep_path);

    const depfile_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_comment_crlf_concat.d",
        .{base_path},
    );
    defer std.testing.allocator.free(depfile_path);

    const cmdline = try std.fmt.allocPrint(
        std.testing.allocator,
        "clang -c {s} -o sample_comment_crlf_concat.o",
        .{source_path},
    );
    defer std.testing.allocator.free(cmdline);

    const depfile_text = try std.fmt.allocPrint(
        std.testing.allocator,
        "sample_comment_crlf_concat.o: {s} {s} \\\\r\n# generated by rustc\\\\\\\\r\n  still comment\r\nmodule/sample_comment_crlf_concat.o: {s} {s} {s}\r\n",
        .{ source_path, first_dep_path, ignored_source_path, escaped_dep_path, later_dep_path },
    );
    defer std.testing.allocator.free(depfile_text);

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_comment_crlf_concat.d",
        .data = depfile_text,
    });

    var capture = try Capture.init(std.testing.allocator, 768);
    defer capture.deinit();

    try fixdep.runFixdep(
        std.testing.allocator,
        std.testing.io,
        &capture,
        depfile_path,
        "sample_comment_crlf_concat.o",
        cmdline,
    );

    const expected = try std.fmt.allocPrint(
        std.testing.allocator,
        "savedcmd_sample_comment_crlf_concat.o := {s}\n\n" ++
            "source_sample_comment_crlf_concat.o := {s}\n\n" ++
            "deps_sample_comment_crlf_concat.o := \\\n" ++
            "  {s} \\\n" ++
            "  {s} \\\n" ++
            "  {s} \\\n" ++
            "\n" ++
            "sample_comment_crlf_concat.o: $(deps_sample_comment_crlf_concat.o)\n\n" ++
            "$(deps_sample_comment_crlf_concat.o):\n",
        .{ cmdline, source_path, first_dep_path, visible_escaped_dep_path, later_dep_path },
    );
    defer std.testing.allocator.free(expected);

    try std.testing.expectEqualStrings(expected, capture.list.items);
}
