const std = @import("std");

test "fixdep keeps escaped-colon dependencies aligned on the public entry path" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const base_path = try std.fmt.allocPrint(
        std.testing.allocator,
        ".zig-cache/tmp/{s}",
        .{tmp.sub_path[0..]},
    );
    defer std.testing.allocator.free(base_path);

    const depfile_path = try std.fmt.allocPrint(
        std.testing.allocator,
        "{s}/sample_escaped_colon_comment.d",
        .{base_path},
    );
    defer std.testing.allocator.free(depfile_path);

    const cmdline = "clang -c sample_escaped_colon_comment_source.c -o sample_escaped_colon_comment.o";

    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "sample_escaped_colon_comment.d",
        .data = "sample_escaped_colon_comment.o: sample_escaped_colon_comment_source.rmeta dir\\:crate.rmeta \\\n" ++
            "# generated by rustc\\\\\n" ++
            "  still comment\n" ++
            "module/sample_escaped_colon_comment.o: temp.rmeta later.rmeta\n",
    });

    const argv: []const []const u8 = &.{
        "zig",
        "run",
        "fixdep.zig",
        "--",
        depfile_path,
        "sample_escaped_colon_comment.o",
        cmdline,
    };
    const result = try std.process.run(std.testing.allocator, std.testing.io, .{
        .argv = argv,
        .cwd = .{ .path = "." },
        .stdout_limit = .unlimited,
        .stderr_limit = .unlimited,
    });
    defer std.testing.allocator.free(result.stdout);
    defer std.testing.allocator.free(result.stderr);

    try std.testing.expectEqual(std.process.Child.Term{ .exited = 0 }, result.term);
    try std.testing.expectEqualStrings(
        "savedcmd_sample_escaped_colon_comment.o := " ++ cmdline ++ "\n\n" ++
            "source_sample_escaped_colon_comment.o := sample_escaped_colon_comment_source.rmeta\n\n" ++
            "deps_sample_escaped_colon_comment.o := \\\n" ++
            "  dir:crate.rmeta \\\n" ++
            "  later.rmeta \\\n" ++
            "\n" ++
            "sample_escaped_colon_comment.o: $(deps_sample_escaped_colon_comment.o)\n\n" ++
            "$(deps_sample_escaped_colon_comment.o):\n",
        result.stdout,
    );
    try std.testing.expectEqualStrings("", result.stderr);
}
