#!/usr/bin/env python3
from __future__ import annotations

import argparse
import shutil
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORKFLOW = ".github/workflows/zigux-bootstrap.yml"
MAKEFILE = "zigux/Makefile"
GENKSYMS_DUAL_IMPLEMENTATION_SURVEY = "Documentation/zigux/phase2-genksyms-dual-implementation-survey.md"
FIXDEP_DUAL_IMPLEMENTATION_SURVEY = "Documentation/zigux/phase2-fixdep-dual-implementation-survey.md"
GENKSYMS_VERSION_SIDE_EFFECT_TEST = "scripts/zigux/genksyms_version_before_invalid_long_option_test.zig"
GENKSYMS_VERSION_SIDE_EFFECT_AMBIGUOUS_TEST = "scripts/zigux/genksyms_version_before_ambiguous_long_option_test.zig"
GENKSYMS_MANIFEST_FIXTURE = "zigux/tests/fixtures/genksyms_bridge/manifest.json"
GENKSYMS_PROCESS_OUTPUT_FIXTURES = (
    "zigux/tests/fixtures/genksyms_bridge/abbreviated_version_expected.json",
    "zigux/tests/fixtures/genksyms_bridge/ambiguous_long_option_expected.json",
    "zigux/tests/fixtures/genksyms_bridge/invalid_option_expected.json",
    "zigux/tests/fixtures/genksyms_bridge/missing_long_dump_types_argument_expected.json",
    "zigux/tests/fixtures/genksyms_bridge/missing_long_reference_argument_expected.json",
    "zigux/tests/fixtures/genksyms_bridge/missing_reference_argument_expected.json",
    "zigux/tests/fixtures/genksyms_bridge/too_many_reference_files_expected.json",
    "zigux/tests/fixtures/genksyms_bridge/unsupported_long_option_expected.json",
    "zigux/tests/fixtures/genksyms_bridge/unexpected_long_help_argument_expected.json",
)
KCONFIG_CONF_EXPECTED_FIXTURES = (
    "zigux/tests/fixtures/kconfig_bridge/oldaskconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/syncconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/oldconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/allnoconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/allyesconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/allmodconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/alldefconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/randconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/defconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/savedefconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/listnewconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/helpnewconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/olddefconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/yes2modconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/mod2yesconfig_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/mod2noconfig_expected.json",
)
KCONFIG_CONFDATA_INPUT_FIXTURES = (
    "zigux/tests/fixtures/kconfig_bridge/sample.config",
    "zigux/tests/fixtures/kconfig_bridge/escaped_strings.config",
    "zigux/tests/fixtures/kconfig_bridge/escaped_control_sequences.config",
    "zigux/tests/fixtures/kconfig_bridge/trailing_escaped_backslash.config",
    "zigux/tests/fixtures/kconfig_bridge/sample_crlf.config",
    "zigux/tests/fixtures/kconfig_bridge/explicit_n_tristate.config",
    "zigux/tests/fixtures/kconfig_bridge/final_trailing_carriage_return.config",
    "zigux/tests/fixtures/kconfig_bridge/final_unterminated_unset_comment.config",
    "zigux/tests/fixtures/kconfig_bridge/uppercase_tristate.config",
    "zigux/tests/fixtures/kconfig_bridge/non_config_lines.config",
    "zigux/tests/fixtures/kconfig_bridge/empty_config_symbol_names.config",
    "zigux/tests/fixtures/kconfig_bridge/malformed_unset_comment_tokens.config",
    "zigux/tests/fixtures/kconfig_bridge/last_state_transitions.config",
    "zigux/tests/fixtures/kconfig_bridge/duplicate_assignments.config",
    "zigux/tests/fixtures/kconfig_bridge/duplicate_malformed_quoted_assignment.config",
)
KCONFIG_CONFDATA_EXPECTED_FIXTURES = (
    "zigux/tests/fixtures/kconfig_bridge/sample_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/escaped_strings_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/escaped_control_sequences_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/trailing_escaped_backslash_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/sample_crlf_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/explicit_n_tristate_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/final_trailing_carriage_return_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/final_unterminated_unset_comment_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/uppercase_tristate_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/non_config_lines_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/empty_config_symbol_names_expected.json",
    "zigux/tests/fixttures/kconfig_bridge/malformed_unset_comment_tokens_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/last_state_transitions_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/duplicate_assignments_expected.json",
    "zigux/tests/fixtures/kconfig_bridge/duplicate_malformed_quoted_assignment_expected.json",
)
FIXDEP_FIXTURE_FILES = (
    "zigux/tests/fixtures/fixdep/dep:colon.so",
    "zigux/tests/fixtures/fixdep/dep\\ name.rmeta",
    "zigux/tests/fixtures/fixdep/escaped\\ space-config.h",
    "zigux/tests/fixtures/fixdep/sample-config.h",
    "zigux/tests/fixtures/fixdep/sample.c",
    "zigux/tests/fixtures/fixdep/sample.d",
    "zigux/tests/fixttures/fixdep/sample.h",
    "zigux/tests/fixttures/fixdep/sample.rmeta",
    "zigux/tests/fixtures/fixdep/sample2-config.h",
    "zigux/tests/fixtures/fixdep/sample2.c",
    "zigux/tests/fixtures/fixdep/sample2.so",
    "zigux/tests/fixttures/fixdep/sample_comment_continuation.d",
    "zigux/tests/fixttures/fixdep/sample_comment_continuation_dep.so",
    "zigux/tests/fixtures/fixdep/sample_comment_continuation_expected.txt",
    "zigux/tests/fixtuures/fixdep/sample_comment_continuation_source.c",
    "zigux/tests/fixtures/fixdep/sample_comment_continuation_source.rmeta",
    "zigux/tests/fixtures/fixdep/sample_comment_only.d",
    "zigux/tests/fixtures/fixdep/sample_comment_only_expected.stderr.txt",
    "zigux/tests/fixtures/fixdep/sample_comment_only_expected.txt",
    "zigux/tests/fixtures/fixdep/sample_concatenated.d",
    "zigux/tests/fixtures/fixdep/sample_concatenated_dep.h",
    "zigux/tests/fixtures/fixdep/sample_concatenated_expected.txt",
    "zigux/tests/fixtures/fixdep/sample_concatenated_source.c",
    "zigux/tests/fixtures/fixdep/sample_concatenated_temp.c",
    "zigux/tests/fixtures/fixdep/sample_concatenated_temp_dep.h",
    "zigux/tests/fixtures/fixdep/sample_dependency_continuation.d",
    "zigux/tests/fixttures/fixdep/sample_dependency_continuation_dep.so",
    "zigux/tests/fixtures/fixdep/sample_dependency_continuation_expected.txt",
    "zigux/tests/fixttures/fixdep/sample_dependency_continuation_source.c",
    "zigux/tests/fixtures/fixdep/sample_dependency_continuation_source.rmeta",
    "zigux/tests/fixtures/fixdep/sample_double_backslash_comment.d",
    "zigux/tests/fixtures/fixdep/sample_double_backslash_comment_expected.stderr.txt",
    "zigux/tests/fixtures/fixdep/sample_double_backslash_comment_expected.txt",
    "zigux/tests/fixtures/fixdep/sample_double_backslash_comment_source.rmeta",
    "zigux/tests/fixttures/fixdep/sample_escaped_colon.d",
    "zigux/tests/fixtures/fixdep/sample_escaped_colon_expected.txt",
    "zigux/tests/fixtures/fixdep/sample_escaped_colon_source.c",
    "zigux/tests/fixtures/fixdep/sample_escaped_colon_source.rmeta",
    "zigux/tests/fixtures/fixdep/sample_escaped_space.d",
    "zigux/tests/fixtures/fixdep/sample_escaped_space_expected.txt",
    "zigux/tests/fixtures/fixdep/sample_escaped_space_source.c",
    "zigux/tests/fixtures/fixdep/sample_escaped_space_source.rmeta",
    "zigux/tests/fixtures/fixdep/sample_expected.txt",
    "zigux/tests/fixtures/fixdep/sample_missing_dep.d",
    "zigux/tests/fixtures/fixdep/sample_missing_dep_expected.stderr.txt",
    "zigux/tests/fixttures/fixdep/sample_missing_dep_expected.txt",
    "zigux/tests/fixtures/fixdep/sample_missing_dep_source.c",
    "zigux/tests/fixtures/fixdep/sample_multi_target.d",
    "zigux/tests/fixtures/fixdep/sample_multi_target_expected.txt",
    "zigux/tests/fixtures/fixdep/sample_output_write_expected.stderr.txt",
    "zigux/tests/fixtures/fixdep/sample_output_write_expected.txt",
    "zigux/tests/fixttures/fixdep/shared#config.h",
    "zigux/tests/fixtures/fixdep/shared:config.h",
)
ARCHIVE_PAYLOAD_PATH = "third_party/zig-x86_64-linux-0.17.0-dev.87+9b177a7d2.tar.xz"
ARCHIVE_PART_MANIFEST_PATH = "third_party/zig-x86_64-linux-0.17.0-dev.87+9b177a7d2.tar.xz.parts/manifest.json"
ARCHIVE_SUPPORT_ALTERNATIVES = (
    ARCHIVE_PAYLOAD_PATH,
    ARCHIVE_PART_MANIFEST_PATH,
)
CLOSURE_MATRIX_CHECKER = "scripts/zigux/check-phase2-closure-matrix.py"

REQUIRED_PATHS = (
    "Documentation/zigux/README.md",
    "Documentation/zigux/phase2-closure.md",
    GENKSYMS_DUAL_IMPLEMENTATION_SURVEY,
    FIXDEP_DUAL_IMPLEMENTATION_SURVEY,
    "Documentation/zigux/phase2-toolchain-bootstrap-notes.md",
    "Documentation/zigux/review-checklist.md",
    "scripts/zigux/README.md",
    "scripts/zigux/check-zig-toolchain.py",
    "scripts/zigux/check-kconfig-bridge.py",
    "scripts/zigux/check-phase2-kbuild-routes.py",
    "scripts/zigux/check-phase2-kconfig-selftest-alignment.py",
    "scripts/zigux/check-phase2-kconfig-allconfig-helper-packet.py",
    "scripts/zigux/check-phase2-genksyms-selftest-alignment.py",
    "scripts/zigux/check-phase2-tests-readme-alignment.py",
    "scripts/zigux/check-phase2-cross.py",
    "scripts/zigux/check-phase2-cross-selftest-alignment.py",
    "scripts/zigux/check-phase2-toolchain-pinning.py",
    "scripts/zigux/check-phase2-toolchain-pin-scope.py",
    "scripts/zigux/check-phase2-required-make-routes.py",
    "scripts/zigux/check-phase2-docs-shared-reminder.py",
    "scripts/zigux/check-phase2-tool-manifest.py",
    "scripts/zigux/check-phase2-artifact-tools-manifest.py",
    "scripts/zigux/check-genksyms-bridge.py",
    "scripts/zigux/check-phase2-fixdep-gate.py",
    "scripts/zigux/check-fixdep-diff.py",
    "scripts/zigux/check-lane05-local-first-archive-workflow.py",
    "scripts/zigux/check-lane05-local-archive-readme.py",
    "scripts/zigux/check-lane05-install-zig-archive-verification.py",
    "scripts/zigux/check-lane05-stage-helper-contract.py",
    "scripts/zigux/check-lane05-stage-helper-selftest.py",
    "scripts/zigux/install-zig.py",
    "scripts/zigux/stage-pinned-zig-archive.py",
    "scripts/zigux/kconfig/conf_bridge.zig",
    "scripts/zigux/kconfig/confdata_bridge.zig",
    "scripts/zigux/genksyms.zig",
    GENKSYMS_VERSION_SIDE_EFFECT_TEST,
    GENKSYMS_VERSION_SIDE_EFFECT_AMBIGUOUS_TEST,
    "scripts/zigux/fixdep.zig",
    "scripts/zigux/zig-toolchain-policy.json",
    "scripts/zigux/artifact_diff.py",
    "third_party/README.md",
    "zigux/tests/README.md",
    "zigux/tests/fixtures/kconfig_bridge/cases.json",
    "zigux/tests/fixtures/kconfig_bridge/conf_manifest.json",
    "zigux/tests/fixttures/kconfig_bridge/confdata_manifest.json",
    *KCONFIG_CONF_EXPECTED_FIXTURES,
    *KCONFIG_CONFDATA_INPUT_FIXTURES,
    *KCONFIG_CONFDATA_EXPECTED_FIXTURES,
    "zigux/tests/fixttures/genksyms_bridge/cases.json",
    "zigux/tests/fixtures/genksyms_bridge/help_expected.json",
    GENKSYMS_MANIFEST_FIXTURE,
    "zigux/tests/fixttures/genksyms_bridge/minimal_expected.json",
    "zigux/tests/fixtures/genksyms_bridge/debug_reference_types_expected.json",
    "zigux/tests/fixttures/genksyms_bridge/long_options_expected.json",
    "zigux/tests/fixttures/genksyms_bridge/abbreviated_long_options_expected.json",
    "zigux/tests/fixttures/genksyms_bridge/quiet_overrides_warning_expected.json",
    "zigux/tests/fixtuure