#!/usr/bin/env python3
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]

EXPECTED_PHASE1_FIXTURE_SHAPE = {
    'find_bit': {
        'bits_per_long',
        'first',
        'next_after_6',
        'next_after_word',
        'first_zero',
        'next_zero',
        'first_and',
        'next_and',
        'tail_clamped_first',
        'tail_clamped_next',
        'tail_zero_clamped_first',
        'tail_zero_clamped_next',
        'tail_and_clamped_first',
        'tail_and_clamped_next',
        'tail_and_mixed_first',
        'tail_and_mixed_next',
    },
    'bitmap': {
        'weight',
        'scnprintf',
        'and_result',
        'and_values',
        'andnot_result',
        'andnot_values',
        'or_values',
        'xor_values',
        'copy_nbits',
        'copy_values',
        'partial_xor_nbits',
        'partial_xor_masked_values',
        'scnprintf_empty_len',
        'scnprintf_empty_bytes',
        'equal',
        'intersects',
        'subset',
        'range_after_set',
        'range_after_clear',
        'full_after_fill',
        'empty_after_zero',
        'scnprintf_trunc_len',
        'scnprintf_trunc',
    },
    'string': {
        'strtobool_y',
        'strtobool_on',
        'strtobool_zero',
        'strtobool_off',
        'strtobool_invalid',
        'strlcpy_len',
        'strlcpy_buffer',
        'skip_spaces',
        'trim_spaces',
        'remove_spaces',
        'remove_spaces_nul',
        'remove_spaces_nul_bytes',
        'replace_char',
        'replace_char_end',
        'memchr_inv_index',
        'memchr_inv_none',
    },
    'rbtree': {
        'empty_root',
        'insert_order',
        'reverse_order',
        'replace_order',
        'erase_init_order',
        'postorder_count',
        'erase_init_node_empty',
        'cleared_node_empty',
    },
    'argv_split': {'argc', 'argv', 'blank_argc'},
    'cmdline': {'decimal_k', 'hex_m', 'octal_k', 'invalid'},
    'ctype': {
        'mask_A',
        'mask_a',
        'mask_space',
        'isalnum_A',
        'isalpha_z',
        'isdigit_7',
        'isspace_tab',
        'isxdigit_f',
        'ispunct_bang',
        'tolower_A',
        'toupper_z',
        'isodigit_7',
        'isodigit_8',
    },
    'hweight': {'w8', 'w16', 'w32', 'w64', 'wlong'},
    'list_sort': {'tri_sorted_keys', 'tri_sorted_ordinals', 'bool_sorted_keys', 'bool_sorted_ordinals'},
    'zalloc': {'zeroed', 'freed_is_null', 'value_zeroed', 'value_freed_is_null'},
    'str_error_r': {'enoent', 'unknown'},
    'slab': {
        'null_without_reclaim',
        'alloc_count_after_kmalloc',
        'zero_after_kmalloc',
        'alloc_count_after_kmalloc_free',
        'array_zeroed',
        'alloc_count_after_kmalloc_array',
        'alloc_count_after_kmalloc_array_free',
        'slab_is_available',
    },
    'vsprintf': {'scnprintf_text', 'scnprintf_len', 'pad_text', 'pad_len'},
}
¶»§q«^