const std = @import("std");
const genksyms = @import("genksyms");

const testing = std.testing;

fn expectTooManyReferenceFilesFailure(
    args: []const []const u8,
    expected_version_count: usize,
) !void {
    const outcome = try genksyms.parseArgs(testing.allocator, args);
    switch (outcome) {
        .failure => |failure| {
            try testing.expectEqual(expected_version_count, failure.version_count);
            try testing.expectEqual(genksyms.ParseFailure.too_many_reference_files, failure.reason);
        },
        else => return error.ExpectedFailure,
    }
}

test "phase2 genksyms wrapper version-prefixed exact reference-limit failures preserve version count" {
    try expectTooManyReferenceFilesFailure(&.{
        "--version",
        "-r",
        "01.symref",
        "-r",
        "02.symref",
        "-r",
        "03.symref",
        "-r",
        "04.symref",
        "-r",
        "05.symref",
        "-r",
        "06.symref",
        "-r",
        "07.symref",
        "-r",
        "08.symref",
        "-r",
        "09.symref",
        "-r",
        "10.symref",
        "-r",
        "11.symref",
        "-r",
        "12.symref",
        "-r",
        "13.symref",
        "-r",
        "14.symref",
        "-r",
        "15.symref",
        "-r",
        "16.symref",
        "-r",
        "17.symref",
    }, 1);
    try expectTooManyReferenceFilesFailure(&.{
        "-V",
        "-r",
        "01.symref",
        "-r",
        "02.symref",
        "-r",
        "03.symref",
        "-r",
        "04.symref",
        "-r",
        "05.symref",
        "-r",
        "06.symref",
        "-r",
        "07.symref",
        "-r",
        "08.symref",
        "-r",
        "09.symref",
        "-r",
        "10.symref",
        "-r",
        "11.symref",
        "-r",
        "12.symref",
        "-r",
        "13.symref",
        "-r",
        "14.symref",
        "-r",
        "15.symref",
        "-r",
        "16.symref",
        "-r",
        "17.symref",
    }, 1);
}

test "phase2 genksyms wrapper abbreviated version prefixes preserve reference-limit failures" {
    try expectTooManyReferenceFilesFailure(&.{
        "--ver",
        "--reference",
        "01.symref",
        "--reference",
        "02.symref",
        "--reference",
        "03.symref",
        "--reference",
        "04.symref",
        "--reference",
        "05.symref",
        "--reference",
        "06.symref",
        "--reference",
        "07.symref",
        "--reference",
        "08.symref",
        "--reference",
        "09.symref",
        "--reference",
        "10.symref",
        "--reference",
        "11.symref",
        "--reference",
        "12.symref",
        "--reference",
        "13.symref",
        "--reference",
        "14.symref",
        "--reference",
        "15.symref",
        "--reference",
        "16.symref",
        "--reference",
        "17.symref",
    }, 1);
    try expectTooManyReferenceFilesFailure(&.{
        "-V",
        "--reference",
        "01.symref",
        "--reference",
        "02.symref",
        "--reference",
        "03.symref",
        "--reference",
        "04.symref",
        "--reference",
        "05.symref",
        "--reference",
        "06.symref",
        "--reference",
        "07.symref",
        "--reference",
        "08.symref",
        "--reference",
        "09.symref",
        "--reference",
        "10.symref",
        "--reference",
        "11.symref",
        "--reference",
        "12.symref",
        "--reference",
        "13.symref",
        "--reference",
        "14.symref",
        "--reference",
        "15.symref",
        "--reference",
        "16.symref",
        "--reference",
        "17.symref",
    }, 1);
}
