const std = @import("std");
const abi = @import("abi_bindings");
const layout_assert = @import("layout_assert");
const panic_policy = @import("panic_policy");
const allocator_policy = @import("allocator_policy");
const atomic = @import("atomic_helpers");
const barrier = @import("barrier_helpers");
const mmio = @import("mmio_helpers");
const bitmap_view = @import("bitmap_view");
const cpumask_view = @import("cpumask_view");
const list_view = @import("list_view");
const hlist_view = @import("hlist_view");
const err_ptr = @import("err_ptr");
const xa_value = @import("xa_value");
const xarray_slot_view = @import("xarray_slot_view");
const idr_slot_view = @import("idr_slot_view");
const ida_bitmap_view = @import("ida_bitmap_view");
const ida_alloc_view = @import("ida_alloc_view");
const ida_range_view = @import("ida_range_view");
const ida_range_set_view = @import("ida_range_set_view");
const ida_policy_view = @import("ida_policy_view");
const minor_alloc_plan = @import("minor_alloc_plan");
const dev_region_plan = @import("dev_region_plan");
const cdev_add_plan = @import("cdev_add_plan");
const cdev_lookup_plan = @import("cdev_lookup_plan");
const chrdev_open_plan = @import("chrdev_open_plan");
const chrdev_fops_plan = @import("chrdev_fops_plan");
const chrdev_route_plan = @import("chrdev_route_plan");
const chrdev_io_plan = @import("chrdev_io_plan");
const chrdev_xfer_plan = @import("chrdev_xfer_plan");
const chrdev_resume_plan = @import("chrdev_resume_plan");
const chrdev_retry_plan = @import("chrdev_retry_plan");
const chrdev_requeue_plan = @import("chrdev_requeue_plan");
const chrdev_complete_plan = @import("chrdev_complete_plan");
const chrdev_notify_plan = @import("chrdev_notify_plan");
const chrdev_notify_policy_plan = @import("chrdev_notify_policy_plan");
const chrdev_notify_budget_plan = @import("chrdev_notify_budget_plan");
const chrdev_notify_ack_plan = @import("chrdev_notify_ack_plan");
const chrdev_notify_ack_budget_plan = @import("chrdev_notify_ack_budget_plan");
const chrdev_notify_ack_window_plan = @import("chrdev_notify_ack_window_plan");
const chrdev_notify_ack_window_policy_plan = @import("chrdev_notify_ack_window_policy_plan");
const chrdev_notify_ack_window_policy_budget_plan = @import("chrdev_notify_ack_window_policy_budget_plan");
const chrdev_notify_ack_window_policy_budget_window_plan = @import("chrdev_notify_ack_window_policy_budget_window_plan");
const chrdev_notify_ack_window_policy_budget_window_delivery_plan = @import("chrdev_notify_ack_window_policy_budget_window_delivery_plan");
const chrdev_notify_ack_window_policy_budget_window_delivery_window_plan = @import("chrdev_notify_ack_window_policy_budget_window_delivery_window_plan");
const chrdev_notify_ack_window_policy_budget_window_delivery_window_budget_plan = @import("chrdev_notify_ack_window_policy_budget_window_delivery_window_budget_plan");
const chrdev_notify_ack_window_policy_budget_window_delivery_window_budget_window_plan = @import("chrdev_notify_ack_window_policy_budget_window_delivery_window_budget_window_plan");
const chrdev_notify_ack_window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_plan = @import("chrdev_notify_ack_window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_plan");
const chrdev_notify_ack_delivery_budget_guard_plan = @import("chrdev_notify_ack_delivery_budget_guard_plan");
const chrdev_notify_ack_delivery_budget_guard_window_plan = @import("chrdev_notify_ack_delivery_budget_guard_window_plan");
const chrdev_notify_ack_delivery_budget_guard_window_policy_plan = @import("chrdev_notify_ack_delivery_budget_guard_window_policy_plan");
const chrdev_notify_ack_delivery_budget_guard_window_policy_budget_plan = @import("chrdev_notify_ack_delivery_budget_guard_window_policy_budget_plan");
const chrdev_notify_ack_delivery_budget_guard_window_policy_budget_window_plan = @import("chrdev_notify_ack_delivery_budget_guard_window_policy_budget_window_plan");
const chrdev_notify_ack_delivery_budget_guard_window_policy_budget_window_delivery_plan = @import("chrdev_notify_ack_delivery_budget_guard_window_policy_budget_window_delivery_plan");
const chrdev_notify_ack_delivery_budget_guard_window_policy_budget_window_delivery_window_plan = @import("chrdev_notify_ack_delivery_budget_guard_window_policy_budget_window_delivery_window_plan");
const chrdev_notify_ack_delivery_budget_guard_window_policy_budget_window_delivery_window_budget_plan = @import("chrdev_notify_ack_delivery_budget_guard_window_policy_budget_window_delivery_window_budget_plan");
const chrdev_notify_ack_delivery_budget_guard_window_policy_budget_window_delivery_window_budget_window_plan = @import("chrdev_notify_ack_delivery_budget_guard_window_policy_budget_window_delivery_window_budget_window_plan");
const export_shim = @import("export_shim");
const narrow = @import("narrow_unsafe");
const uapi_version = @import("uapi_version");

test "phase3 abi slice uses stable canonical layouts" {
    comptime {
        @setEvalBranchQuota(4000);
        layout_assert.assertBoundaryHeaderLayout();
        layout_assert.assertExportStatusLayout();
        layout_assert.assertInteropPolicyLayout();
        layout_assert.assertOffset(abi.BitmapView, "nbits", @sizeOf(usize));
        layout_assert.assertOffset(abi.BitmapView, "word_count", @sizeOf(usize) + 4);
        layout_assert.assertOffset(abi.CpuMaskView, "nr_cpu_ids", @sizeOf(usize));
        layout_assert.assertSize(abi.BitmapSummary, 16);
        layout_assert.assertSize(abi.CpuMaskSummary, 16);
        layout_assert.assertSize(abi.ListSummary, 8);
        layout_assert.assertSize(abi.HListSummary, 8);
        layout_assert.assertSize(abi.ErrPtrSummary, 8);
        layout_assert.assertSize(abi.XaValueSummary, @sizeOf(usize) + 8);
        layout_assert.assertSize(abi.XaSlotView, @sizeOf(usize) + 8);
        layout_assert.assertSize(abi.XaSlotSummary, 24);
        layout_assert.assertSize(abi.IdrSlotView, @sizeOf(usize) + 16);
        layout_assert.assertSize(abi.IdrSlotSummary, 32);
        layout_assert.assertSize(abi.IdaBitmapView, @sizeOf(usize) + 16);
        layout_assert.assertSize(abi.IdaBitmapSummary, 24);
        layout_assert.assertSize(abi.IdaAllocView, @sizeOf(usize) + 24);
        layout_assert.assertSize(abi.IdaAllocSummary, 24);
        layout_assert.assertSize(abi.IdaRangeView, @sizeOf(usize) + 24);
        layout_assert.assertSize(abi.IdaRangeSummary, 24);
        layout_assert.assertSize(abi.IdaRangeSetView, @sizeOf(usize) + 32);
        layout_assert.assertSize(abi.IdaRangeSetSummary, 32);
        layout_assert.assertSize(abi.IdaPolicyView, @sizeOf(usize) + 24);
        layout_assert.assertSize(abi.IdaPolicySummary, 24);
        layout_assert.assertSize(abi.MinorAllocView, @sizeOf(usize) + 32);
        layout_assert.assertSize(abi.MinorAllocSummary, 32);
        layout_assert.assertSize(abi.DevRegionView, @sizeOf(usize) + 32);
        layout_assert.assertSize(abi.DevRegionSummary, 32);
        layout_assert.assertSize(abi.CdevAddView, @sizeOf(usize) + 32);
        layout_assert.assertSize(abi.CdevAddSummary, 32);
        layout_assert.assertSize(abi.CdevLookupView, @sizeOf(usize) + 32);
        layout_assert.assertSize(abi.CdevLookupSummary, 36);
        layout_assert.assertSize(abi.ChrdevOpenView, @sizeOf(usize) + 40);
        layout_assert.assertSize(abi.ChrdevOpenSummary, 40);
        layout_assert.assertSize(abi.ChrdevFopsView, @sizeOf(usize) + 48);
        layout_assert.assertSize(abi.ChrdevFopsSummary, 40);
        layout_assert.assertSize(abi.ChrdevRouteView, @sizeOf(usize) + 48);
        layout_assert.assertSize(abi.ChrdevRouteSummary, 44);
        layout_assert.assertSize(abi.ChrdevIoView, @sizeOf(usize) + 56);
        layout_assert.assertSize(abi.ChrdevIoSummary, 56);
        layout_assert.assertSize(abi.ChrdevXferView, @sizeOf(usize) + 80);
        layout_assert.assertSize(abi.ChrdevXferSummary, 96);
        layout_assert.assertSize(abi.ChrdevResumeView, @sizeOf(usize) + 80);
        layout_assert.assertSize(abi.ChrdevResumeSummary, 88);
        layout_assert.assertSize(abi.ChrdevRetryView, @sizeOf(usize) + 96);
        layout_assert.assertSize(abi.ChrdevRetrySummary, 104);
        layout_assert.assertSize(abi.ChrdevRequeueView, @sizeOf(usize) + 104);
        layout_assert.assertSize(abi.ChrdevRequeueSummary, 128);
        layout_assert.assertSize(abi.ChrdevCompleteView, @sizeOf(usize) + 120);
        layout_assert.assertSize(abi.ChrdevCompleteSummary, 152);
        layout_assert.assertSize(abi.ChrdevNotifyView, @sizeOf(usize) + 136);
        layout_assert.assertSize(abi.ChrdevNotifySummary, 192);
        layout_assert.assertSize(abi.ChrdevNotifyPolicyView, @sizeOf(usize) + 144);
        layout_assert.assertSize(abi.ChrdevNotifyPolicySummary, 232);
        layout_assert.assertSize(abi.ChrdevNotifyBudgetView, @sizeOf(usize) + 152);
        layout_assert.assertSize(abi.ChrdevNotifyBudgetSummary, 272);
        layout_assert.assertSize(abi.ChrdevNotifyAckView, @sizeOf(usize) + 176);
        layout_assert.assertSize(abi.ChrdevNotifyAckSummary, 320);
        layout_assert.assertSize(abi.ChrdevNotifyAckBudgetView, @sizeOf(usize) + 200);
        layout_assert.assertSize(abi.ChrdevNotifyAckBudgetSummary, 408);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowView, @sizeOf(usize) + 208);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowSummary, 448);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyView, @sizeOf(usize) + 216);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicySummary, 496);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetView, @sizeOf(usize) + 224);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetSummary, 544);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowView, @sizeOf(usize) + 240);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowSummary, 584);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryView, @sizeOf(usize) + 248);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliverySummary, 632);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowView, @sizeOf(usize) + 264);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetView, @sizeOf(usize) + 272);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowView, @sizeOf(usize) + 288);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryView, @sizeOf(usize) + 296);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowSummary, 680);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetSummary, 728);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowSummary, 768);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliverySummary, 816);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowView, 320);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetView, 328);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardView, 344);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowView, 360);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyView, 368);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetView, 384);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowView, 400);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryView, 416);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowView, 432);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetView, 448);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowView, 464);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryView, 480);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowView, 496);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetView, 512);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowSummary, 864);
        layout_assert.assertSize(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, 912);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, 976);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowSummary, 1032);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicySummary, 1072);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetSummary, 1128);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowSummary, 1176);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliverySummary, 1232);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowSummary, 1280);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetSummary, 1336);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowSummary, 1384);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliverySummary, 1440);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowSummary, 1488);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, 1544);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowView, 528);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowSummary, 1592);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliveryView, 544);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliverySummary, 1648);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowView, 560);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowSummary, 1696);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetView, 576);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, 1752);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowView, 592);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowSummary, 1800);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliveryView, 608);
        layout_assert.assertSize(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetWindowDeliverySummary, 1856);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetView, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget", 316);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetView, "deferred_window_policy_budget_window_delivery_window_budget_window_delivery_window_budget", 320);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetView, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_reserved", 324);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_flags", 860);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_before", 864);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_after", 868);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "deferred_window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_before", 872);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "deferred_window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_after", 876);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_status", 880);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_acked_count", 884);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_deferred_count", 888);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_suppressed_count", 892);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_coalesced_count", 896);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_dropped_count", 900);
        layout_assert.assertOffset(abi.ChrdevNotifyAckWindowPolicyBudgetWindowDeliveryWindowBudgetWindowDeliveryWindowBudgetSummary, "window_policy_budget_window_delivery_window_budget_window_delivery_window_budget_skipped_count", 904);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardView, "primary_guard_floor", 328);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardView, "deferred_guard_floor", 332);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardView, "reserved", 336);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowView, "primary_window", 344);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowView, "deferred_window", 348);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowView, "window_floor", 352);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowView, "reserved", 356);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyView, "policy_flags", 360);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyView, "reserved", 364);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetView, "primary_budget", 368);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetView, "deferred_budget", 372);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetView, "reserved", 376);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowView, "budget_window", 384);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowView, "budget_window_floor", 388);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowView, "reserved", 392);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryView, "primary_delivery_budget", 400);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryView, "deferred_delivery_budget", 404);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardWindowPolicyBudgetWindowDeliveryView, "reserved", 408);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "primary_before", 912);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "primary_after", 916);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "deferred_before", 920);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "deferred_after", 924);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "primary_guard_floor", 928);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "deferred_guard_floor", 932);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "guard_flags", 936);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "guard_status", 940);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "acked_count", 944);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "deferred_count", 948);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "suppressed_count", 952);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "coalesced_count", 956);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "dropped_count", 960);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "skipped_count", 964);
        layout_assert.assertOffset(abi.ChrdevNotifyAckDeliveryBudgetGuardSummary, "held_count", 968);
    }
}

[... truncated for brevity in this message ...]
