sample_comment_continuation.o: zigux/tests/fixtures/fixdep/sample_comment_continuation_source.rmeta \
 zigux/tests/fixtures/fixdep/sample_comment_continuation_dep.so \
 zigux/tests/fixtures/fixdep/sample_comment_continuation_dep.so \
 include/generated/autoconf.h \
 zigux/tests/fixtures/fixdep/sample_comment_continuation_dep.so \
 include/generated/autoconf.h \
# generated by rustc\\
  still comment
