sample_concatenated.o: zigux/tests/fixtures/fixdep/sample_concatenated_source.c zigux/tests/fixtures/fixdep/sample_concatenated_dep.h zigux/tests/fixtures/fixdep/escaped\ space-config.h zigux/tests/fixtures/fixdep/shared\#config.h zigux/tests/fixtures/fixdep/shared\:config.h \
# generated by rustc\\
  still comment
module/sample_concatenated.o: zigux/tests/fixtures/fixdep/sample_concatenated_temp.c zigux/tests/fixtures/fixdep/sample_concatenated_temp_dep.h zigux/tests/fixtures/fixdep/escaped\ space-config.h zigux/tests/fixtures/fixdep/shared\#config.h zigux/tests/fixtures/fixdep/shared\:config.h
