sample_escaped_hash.o: zigux/tests/fixtures/fixdep/sample_escaped_hash_source.rmeta \
 zigux/tests/fixtures/fixdep/dep\#hash.rmeta \
# generated by rustc\\
  still comment
module/sample_escaped_hash.o: zigux/tests/fixtures/fixdep/sample_escaped_hash_temp.rmeta zigux/tests/fixtures/fixdep/later_hash.rmeta
