sample_escaped_hash_comment_chain.o: zigux/tests/fixtures/fixdep/sample.rmeta zigux/tests/fixtures/fixdep/dir\#crate.rmeta \
# generated by rustc\\
  still comment
module/sample_escaped_hash_comment_chain.o: zigux/tests/fixtures/fixdep/temp.rmeta zigux/tests/fixtures/fixdep/later.rmeta
